version: "3"

services: 
  rabbitmq:
    image: rabbitmq:3.8-rc-alpine
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    hostname: rabbitmq
    ports:
      - "5672:5672"
    logging: 
      driver: "none"
  redis:
    image: redis:5-alpine
    hostname: redis
    ports: 
      - "6379:6379"
  celery_worker:
    build: engage_app
    image: hack4laengage/engage_celery:latest
    volumes: 
      - ./engage_app:/engage_app
    working_dir: /engage_app
    entrypoint: ./scripts/runworkerstest.sh
    links: 
      - rabbitmq
      - redis
    depends_on: 
      - rabbitmq
      - redis
    environment: 
      - RABBITMQ_URI=admin:mypass@rabbitmq:5672
      - REDIS_URI=redis:6379
      - SCHEDULER=tests
      - TASKS=tests.tasks
  celery_beat:
    build: engage_app
    image: hack4laengage/engage_celery:latest
    volumes: 
      - ./engage_app:/engage_app
    working_dir: /engage_app
    entrypoint: ./scripts/runbeats.sh
    links: 
      - rabbitmq
      - redis
      - celery_worker
    depends_on: 
      - rabbitmq
      - redis
      - celery_worker
    environment: 
      - RABBITMQ_URI=admin:mypass@rabbitmq:5672
      - REDIS_URI=redis:6379
      - SCHEDULER=tests
      - TASKS=tests.tasks
