version: "3.7"

services: 
  rabbitmq:
    image: rabbitmq:3.8-rc-alpine
    env_file: ../engconfig/engage_celery.env
    hostname: rabbitmq
    ports:
      - "5672:5672"
    logging: 
      driver: "none"
  redis:
    env_file: ../engconfig/engage_celery.env
    image: redis:5-alpine
    hostname: redis
    # command: sh -c 'redis-server --requirepass $$REDIS_PASSWORD'
    command: "sh -c 'printenv REDIS_PASSWORD 2>&1 > ./redis_pass; sed -i \"1s/^/requirepass /\" ./redis_pass; redis-server ./redis_pass'; "
    ports: 
      - "6379:6379"
  celery_worker:
    build: engage_app
    volumes: 
      - ./engage_app:/engage_app
      - ../pdfs:/pdfs
    working_dir: /engage_app
    entrypoint: ./scripts/runworkers.sh
    links: 
      - rabbitmq
      - redis
    depends_on: 
      - rabbitmq
      - redis
    env_file: ../engconfig/engage_celery.env
  celery_beat:
    build: engage_app
    volumes: 
      - ./engage_app:/engage_app
    working_dir: /engage_app
    entrypoint: ./scripts/runbeats.sh
    links: 
      - rabbitmq
      - redis
      - celery_worker
    depends_on: 
      - rabbitmq
      - redis
      - celery_worker
    env_file: ../engconfig/engage_celery.env